const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { validationResult } = require('express-validator');
const pool = require('../config/database');
const path = require('path');
const fs = require('fs');

// Generate JWT token
const generateToken = (userId) => {
  return jwt.sign({ userId }, process.env.JWT_SECRET, {
    expiresIn: process.env.JWT_EXPIRE || '7d'
  });
};

// Register new user
exports.register = async (req, res) => {
  const client = await pool.connect();
  
  try {
    // Validate input
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        errors: errors.array()
      });
    }

    const {
      full_name,
      marga,
      email,
      password,
      gender,
      date_of_birth,
      phone,
      address,
      city,
      province
    } = req.body;

    // Check if email already exists
    const emailCheck = await client.query(
      'SELECT id FROM users WHERE email = $1',
      [email]
    );

    if (emailCheck.rows.length > 0) {
      return res.status(400).json({
        success: false,
        message: 'Email already registered'
      });
    }

    // Check if marga exists in reference table
    const margaCheck = await client.query(
      'SELECT id FROM marga_reference WHERE marga_name = $1',
      [marga]
    );

    if (margaCheck.rows.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'Invalid marga. Please select from the reference list.'
      });
    }

    // Hash password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    // Insert user (batak_id_card will be auto-generated by trigger)
    const result = await client.query(
      `INSERT INTO users (
        full_name, marga, email, password, gender, date_of_birth,
        phone, address, city, province
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      RETURNING id, full_name, marga, email, gender, batak_id_card, created_at`,
      [full_name, marga, email, hashedPassword, gender, date_of_birth,
       phone, address, city, province]
    );

    const user = result.rows[0];

    // Generate token
    const token = generateToken(user.id);

    res.status(201).json({
      success: true,
      message: 'Registration successful',
      data: {
        user: {
          id: user.id,
          full_name: user.full_name,
          marga: user.marga,
          email: user.email,
          gender: user.gender,
          batak_id_card: user.batak_id_card,
          created_at: user.created_at
        },
        token
      }
    });

  } catch (error) {
    console.error('Registration error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error during registration',
      error: error.message
    });
  } finally {
    client.release();
  }
};

// Login user
exports.login = async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        errors: errors.array()
      });
    }

    const { email, password } = req.body;

    // Find user
    const result = await pool.query(
      `SELECT id, full_name, email, password, marga, avatar, batak_id_card, is_active
       FROM users WHERE email = $1`,
      [email]
    );

    if (result.rows.length === 0) {
      return res.status(401).json({
        success: false,
        message: 'Invalid email or password'
      });
    }

    const user = result.rows[0];

    if (!user.is_active) {
      return res.status(403).json({
        success: false,
        message: 'Account is inactive. Please contact support.'
      });
    }

    // Check password
    const isMatch = await bcrypt.compare(password, user.password);

    if (!isMatch) {
      return res.status(401).json({
        success: false,
        message: 'Invalid email or password'
      });
    }

    // Generate token
    const token = generateToken(user.id);

    res.json({
      success: true,
      message: 'Login successful',
      data: {
        user: {
          id: user.id,
          full_name: user.full_name,
          email: user.email,
          marga: user.marga,
          avatar: user.avatar,
          batak_id_card: user.batak_id_card
        },
        token
      }
    });

  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error during login'
    });
  }
};

// Get current user profile
exports.getProfile = async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT id, full_name, marga, email, gender, date_of_birth,
              phone, address, city, province, avatar, batak_id_card, created_at
       FROM users WHERE id = $1`,
      [req.user.id]
    );

    res.json({
      success: true,
      data: result.rows[0]
    });

  } catch (error) {
    console.error('Get profile error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error fetching profile'
    });
  }
};

// Update user profile
exports.updateProfile = async (req, res) => {
  try {
    const {
      full_name,
      phone,
      address,
      city,
      province
    } = req.body;

    let avatar = null;
    
    // Handle avatar upload
    if (req.file) {
      avatar = `/uploads/avatars/${req.file.filename}`;
      
      // Delete old avatar if exists
      const oldAvatarResult = await pool.query(
        'SELECT avatar FROM users WHERE id = $1',
        [req.user.id]
      );
      
      if (oldAvatarResult.rows[0].avatar) {
        const oldAvatarPath = path.join(__dirname, '../../', oldAvatarResult.rows[0].avatar);
        if (fs.existsSync(oldAvatarPath)) {
          fs.unlinkSync(oldAvatarPath);
        }
      }
    }

    // Build update query dynamically
    const updates = [];
    const values = [];
    let paramCount = 1;

    if (full_name) {
      updates.push(`full_name = $${paramCount++}`);
      values.push(full_name);
    }
    if (phone) {
      updates.push(`phone = $${paramCount++}`);
      values.push(phone);
    }
    if (address) {
      updates.push(`address = $${paramCount++}`);
      values.push(address);
    }
    if (city) {
      updates.push(`city = $${paramCount++}`);
      values.push(city);
    }
    if (province) {
      updates.push(`province = $${paramCount++}`);
      values.push(province);
    }
    if (avatar) {
      updates.push(`avatar = $${paramCount++}`);
      values.push(avatar);
    }

    if (updates.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'No fields to update'
      });
    }

    values.push(req.user.id);

    const query = `
      UPDATE users 
      SET ${updates.join(', ')}
      WHERE id = $${paramCount}
      RETURNING id, full_name, marga, email, gender, date_of_birth,
                phone, address, city, province, avatar, batak_id_card
    `;

    const result = await pool.query(query, values);

    res.json({
      success: true,
      message: 'Profile updated successfully',
      data: result.rows[0]
    });

  } catch (error) {
    console.error('Update profile error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error updating profile'
    });
  }
};

// Get marga reference list
exports.getMargaList = async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT id, marga_name, sub_ethnic FROM marga_reference ORDER BY sub_ethnic, marga_name'
    );

    // Group by sub_ethnic
    const grouped = result.rows.reduce((acc, row) => {
      if (!acc[row.sub_ethnic]) {
        acc[row.sub_ethnic] = [];
      }
      acc[row.sub_ethnic].push({
        id: row.id,
        marga_name: row.marga_name
      });
      return acc;
    }, {});

    res.json({
      success: true,
      data: grouped
    });

  } catch (error) {
    console.error('Get marga list error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error fetching marga list'
    });
  }
};
